    INSERT INTO usuarios (nombre, email, password, telefono, ciudad, pais, foto_perfil)
    VALUES 
    ('Juan Pérez', 'juan@gmail.com', '$2a$10$3sFvB/9yzzsrBs.4ZDYm4erNtDVNXDaAMCKC9BHuP47/XnT7HzbiO', '123456789', 'Madrid', 'España', '/assets/juan.webp'),
    ('Ayoub Boudhafri', 'admin@gmail.com', '$2a$10$3sFvB/9yzzsrBs.4ZDYm4erNtDVNXDaAMCKC9BHuP47/XnT7HzbiO', '987654321', 'Barcelona', 'España', '/assets/maria.webp');

    INSERT INTO inmueble (descripcion_short, descripcion, direccion, ciudad, pais, precio, fecha_publicacion, usuario_id)
    VALUES
    ('Ático moderno', 'Ático con terraza privada y vistas panorámicas', 'Calle Luna 10', 'Valencia', 'España', 450000, NOW(),1),
    ('Chalet exclusivo', 'Chalet con jardín, piscina y área de barbacoa', 'Camino Verde 75', 'Sevilla', 'España', 700000, NOW(),1),
    ('Estudio céntrico', 'Estudio moderno cerca de zonas comerciales', 'Plaza Mayor 22', 'Granada', 'España', 120000, NOW(),1),
    ('Casa rural', 'Casa de campo con terreno y huerta', 'Camino Rural s/n', 'Toledo', 'España', 180000, NOW(),1),
    ('Loft minimalista', 'Loft de diseño en el centro urbano', 'Calle Sol 18', 'Zaragoza', 'España', 320000, NOW(),1),
    ('Dúplex elegante', 'Dúplex con terraza y excelente iluminación', 'Avenida Marítima 101', 'Málaga', 'España', 500000, NOW(),1),
    ('Apartamento familiar', 'Apartamento amplio ideal para familias', 'Calle Otoño 3', 'Bilbao', 'España', 350000, NOW(),1),
    ('Villa de lujo', 'Villa exclusiva en zona residencial', 'Urbanización La Palma 8', 'Santander', 'España', 950000, NOW(),1),
    ('Piso reformado', 'Piso completamente renovado con acabados modernos', 'Calle Flores 14', 'Cádiz', 'España', 290000, NOW(), 1),
    ('Bungalow acogedor', 'Bungalow con terraza y vistas al jardín', 'Calle Jardines 2', 'Alicante', 'España', 220000, NOW(), 1);


    INSERT INTO inmueble_imagenes (inmueble_id, imagen_url)
    VALUES 
    (1, '/assets/aticoModerno1.webp'),
    (1, '/assets/aticoModerno2.webp'),
    (1, '/assets/aticoModerno3.webp'),
    (2, '/assets/chaletExclusivo1.webp'),
    (2, '/assets/chaletExclusivo2.webp'),
    (2, '/assets/chaletExclusivo3.webp'),
    (2, '/assets/chaletExclusivo4.webp'),
    (3, '/assets/estudioCentrico1.webp'),
    (3, '/assets/estudioCentrico2.webp'),
    (3, '/assets/estudioCentrico3.webp'),
    (4, '/assets/casaRural1.webp'),
    (4, '/assets/casaRural2.webp'),
    (4, '/assets/casaRural3.webp'),
    (4, '/assets/casaRural4.webp'),
    (5, '/assets/loftMinimalista1.webp'),
    (5, '/assets/loftMinimalista2.webp'),
    (5, '/assets/loftMinimalista3.webp'),
    (6, '/assets/duplexElegante1.webp'),
    (6, '/assets/duplexElegante2.webp'),
    (6, '/assets/duplexElegante3.webp'),
    (7, '/assets/apartamentoFamiliar1.webp'),
    (7, '/assets/apartamentoFamiliar2.webp'),
    (7, '/assets/apartamentoFamiliar3.webp'),
    (8, '/assets/villaDeLujo1.webp'),
    (8, '/assets/villaDeLujo2.webp'),
    (8, '/assets/villaDeLujo3.webp'),
    (8, '/assets/villaDeLujo4.webp'),
    (9, '/assets/pisoReformado1.webp'),
    (9, '/assets/pisoReformado2.webp'),
    (9, '/assets/pisoReformado3.webp'),
    (10, '/assets/bungalowAcogedor1.webp'),
    (10, '/assets/bungalowAcogedor2.webp'),
    (10, '/assets/bungalowAcogedor3.webp'),
    (10, '/assets/bungalowAcogedor4.webp'),
    (10, '/assets/bungalowAcogedor5.webp');


    INSERT INTO libro (precio, nombre, autor, descripcion, fecha_publicacion, entrega_disponible, fecha_publicacion_producto, usuario_id)
    VALUES
    (15.99, 'El principito', 'Juan Lopez', 'Libro clásico de Antoine de Saint-Exupéry', '1943-04-06', TRUE, NOW(), 1),
    (25.00, '1984', 'Jose Fernandez', 'Novela distópica de George Orwell', '1949-06-08', FALSE, NOW(), 1),
    (20.00, 'Cien Años de Soledad', 'Gabriel García Márquez', 'Una novela emblemática del realismo mágico', '1967-05-30', TRUE, NOW(), 1),
    (30.00, 'Don Quijote de la Mancha', 'Miguel de Cervantes', 'Clásico de la literatura española', '1605-01-16', TRUE, NOW(), 1),
    (18.00, 'La sombra del viento', 'Carlos Ruiz Zafón', 'Misterio literario ambientado en Barcelona', '2001-04-04', TRUE, NOW(), 1),
    (22.00, 'El amor en los tiempos del cólera', 'Gabriel García Márquez', 'Historia de amor en medio de adversidades', '1985-09-05', FALSE, NOW(), 1),
    (19.99, 'El código Da Vinci', 'Dan Brown', 'Thriller lleno de enigmas y conspiraciones', '2003-03-18', TRUE, NOW(), 1),
    (15.00, 'Harry Potter y la piedra filosofal', 'J.K. Rowling', 'El inicio de la saga mágica', '1997-06-26', TRUE, NOW(), 1),
    (35.00, 'El señor de los anillos', 'J.R.R. Tolkien', 'La épica aventura en la Tierra Media', '1954-07-29', FALSE, NOW(), 1),
    (16.00, 'Matar a un ruiseñor', 'Harper Lee', 'Novela que aborda el racismo y la justicia', '1960-07-11', TRUE, NOW(), 1);

    INSERT INTO libro_imagenes (libro_id, imagen_url)
    VALUES
    (1, '/assets/principito.webp'),
    (1, '/assets/principito2.webp'),
    (2, '/assets/1984.webp'),
    (2, '/assets/1984_2.webp'),
    (3, '/assets/cienanosesoledad.webp'),
    (3, '/assets/cienanosesoledad2.webp'),
    (3, '/assets/cienanosesoledad3.webp'),
    (4, '/assets/donquijotedelamancha.webp'),
    (4, '/assets/donquijotedelamancha2.webp'),
    (4, '/assets/donquijotedelamancha3.webp'),
    (4, '/assets/donquijotedelamancha4.webp'),
    (5, '/assets/lasombreadelviento.webp'),
    (5, '/assets/lasombreadelviento2.webp'),
    (5, '/assets/lasombreadelviento3.webp'),
    (6, '/assets/elamorenlostiemposdelcolera.webp'),
    (6, '/assets/elamorenlostiemposdelcolera2.webp'),
    (6, '/assets/elamorenlostiemposdelcolera3.webp'),
    (6, '/assets/elamorenlostiemposdelcolera4.webp'),
    (7, '/assets/elcodigodavinci.webp'),
    (7, '/assets/elcodigodavinci2.webp'),
    (7, '/assets/elcodigodavinci3.webp'),
    (8, '/assets/harrypotterylapiedraformilosofal.webp'),
    (8, '/assets/harrypotterylapiedraformilosofal2.webp'),
    (8, '/assets/harrypotterylapiedraformilosofal3.webp'),
    (8, '/assets/harrypotterylapiedraformilosofal4.webp'),
    (9, '/assets/elsenordelosanillos.webp'),
    (9, '/assets/elsenordelosanillos2.webp'),
    (9, '/assets/elsenordelosanillos3.webp'),
    (10, '/assets/mataraunruisenor.webp'),
    (10, '/assets/mataraunruisenor2.webp'),
    (10, '/assets/mataraunruisenor3.webp'),
    (10, '/assets/mataraunruisenor4.webp');

    INSERT INTO motor (marca, modelo, precio, kilometraje, descripcion, fecha_publicacion, usuario_id)
        VALUES
        ('Toyota', 'Corolla', 12000, 50000, 'Toyota Corolla en excelente estado', NOW(), 1),
        ('Honda', 'Civic', 15000, 30000, 'Honda Civic 2020, poco uso', NOW(), 1),
        ('Ford', 'Focus', 11000, 60000, 'Ford Focus confiable y económico', NOW(), 1),
        ('Chevrolet', 'Spark', 8000, 45000, 'Chevrolet Spark compacto y ágil', NOW(), 1),
        ('Nissan', 'Sentra', 13000, 40000, 'Nissan Sentra con buen rendimiento', NOW(), 1),
        ('BMW', '3 Series', 25000, 35000, 'BMW 3 Series en óptimas condiciones', NOW(), 1),
        ('Audi', 'A4', 27000, 32000, 'Audi A4 de lujo y alto rendimiento', NOW(), 1),
        ('Volkswagen', 'Golf', 16000, 38000, 'Volkswagen Golf eficiente y moderno', NOW(), 1),
        ('Kia', 'Optima', 14000, 42000, 'Kia Optima espacioso y cómodo', NOW(), 1),
        ('Hyundai', 'Elantra', 12500, 48000, 'Hyundai Elantra con buen equipamiento', NOW(), 1);

    INSERT INTO motor_imagenes (motor_id, imagen_url)
        VALUES
        (1, '/assets/toyota_corolla.webp'),
        (1, '/assets/toyota_corolla2.webp'),
        (1, '/assets/toyota_corolla3.webp'),
        (1, '/assets/toyota_corolla4.webp'),
        (1, '/assets/toyota_corolla5.webp'),
        (1, '/assets/toyota_corolla6.webp'),
        (2, '/assets/honda_civic.webp'),
        (2, '/assets/honda_civic2.webp'),
        (2, '/assets/honda_civic3.webp'),
        (2, '/assets/honda_civic4.webp'),
        (2, '/assets/honda_civic5.webp'),
        (2, '/assets/honda_civic6.webp'),
        (2, '/assets/honda_civic7.webp'),
        (2, '/assets/honda_civic8.webp'),
        (3, '/assets/ford_focus.webp'),
        (3, '/assets/ford_focus2.webp'),
        (3, '/assets/ford_focus3.webp'),
        (3, '/assets/ford_focus4.webp'),
        (3, '/assets/ford_focus5.webp'),
        (3, '/assets/ford_focus6.webp'),
        (4, '/assets/chevrolet_spark.webp'),
        (4, '/assets/chevrolet_spark2.webp'),
        (4, '/assets/chevrolet_spark3.webp'),
        (4, '/assets/chevrolet_spark4.webp'),
        (4, '/assets/chevrolet_spark5.webp'),
        (4, '/assets/chevrolet_spark6.webp'),
        (5, '/assets/nissan_sentra.webp'),
        (5, '/assets/nissan_sentra2.webp'),
        (5, '/assets/nissan_sentra3.webp'),
        (5, '/assets/nissan_sentra4.webp'),
        (5, '/assets/nissan_sentra5.webp'),
        (5, '/assets/nissan_sentra6.webp'),
        (6, '/assets/bmw_3series.webp'),
        (6, '/assets/bmw_3series2.webp'),
        (6, '/assets/bmw_3series3.webp'),
        (6, '/assets/bmw_3series4.webp'),
        (6, '/assets/bmw_3series5.webp'),
        (6, '/assets/bmw_3series6.webp'),
        (7, '/assets/audi_a4.webp'),
        (7, '/assets/audi_a42.webp'),
        (7, '/assets/audi_a43.webp'),
        (7, '/assets/audi_a44.webp'),
        (7, '/assets/audi_a45.webp'),
        (7, '/assets/audi_a46.webp'),
        (8, '/assets/volkswagen_golf.webp'),
        (8, '/assets/volkswagen_golf2.webp'),
        (8, '/assets/volkswagen_golf3.webp'),
        (8, '/assets/volkswagen_golf4.webp'),
        (8, '/assets/volkswagen_golf5.webp'),
        (8, '/assets/volkswagen_golf6.webp'),
        (9, '/assets/kia_optima.webp'),
        (9, '/assets/kia_optima2.webp'),
        (9, '/assets/kia_optima3.webp'),
        (9, '/assets/kia_optima4.webp'),
        (9, '/assets/kia_optima5.webp'),
        (9, '/assets/kia_optima6.webp'),
        (10, '/assets/hyundai_elantra.webp'),
        (10, '/assets/hyundai_elantra2.webp'),
        (10, '/assets/hyundai_elantra3.webp'),
        (10, '/assets/hyundai_elantra4.webp'),
        (10, '/assets/hyundai_elantra5.webp'),
        (10, '/assets/hyundai_elantra6.webp');



    INSERT INTO tecnologia (id, nombre, precio, categoria, descripcion, envio_disponible, usuario_id, fecha_publicacion)
    VALUES 
    (1, 'iPhone 13', 799, 1, 'iPhone 13 en excelente estado', TRUE, 1, NOW()),
    (2, 'Samsung Galaxy S21', 699, 1, 'Samsung Galaxy S21 con caja y accesorios', FALSE, 1, NOW()),
    (3, 'MacBook Pro 16', 2000, 1, 'MacBook Pro con chip M1 Pro', TRUE, 1, NOW()),
    (4, 'iPad Air 4', 599, 1, 'iPad Air 4ta generación con chip A14 Bionic', TRUE, 1, NOW()),
    (5, 'Google Pixel 6', 599, 1, 'Google Pixel 6 con cámara de 50MP', FALSE, 1, NOW()),
    (6, 'Sony PlayStation 5', 499, 1, 'PlayStation 5 con soporte para 4K y ray tracing', TRUE, 1, NOW()),
    (7, 'Xbox Series X', 499, 1, 'Xbox Series X con SSD ultrarrápido', TRUE, 1, NOW()),
    (8, 'Dell XPS 13', 1299, 1, 'Ultrabook Dell XPS 13 con pantalla táctil', TRUE, 1, NOW()),
    (9, 'Apple Watch Series 7', 399, 1, 'Apple Watch con pantalla Retina Always-On', FALSE, 1, NOW()),
    (10, 'AirPods Pro', 249, 1, 'Auriculares inalámbricos con cancelación de ruido', TRUE, 1, NOW()),
    (11, 'Samsung Galaxy Tab S8', 799, 1, 'Samsung Galaxy Tab S8 con pantalla AMOLED', FALSE, 1, NOW()),
    (12, 'Lenovo Legion 5', 1200, 1, 'Laptop gaming Lenovo Legion 5 con RTX 3060', TRUE, 1, NOW()),
    (13, 'GoPro Hero 10', 499, 1, 'Cámara de acción GoPro Hero 10 con estabilización avanzada', TRUE, 1, NOW()),
    (14, 'Sony WH-1000XM4', 349, 1, 'Auriculares Sony con cancelación de ruido', FALSE, 1, NOW()),
    (15, 'Amazon Echo Dot', 49, 1, 'Asistente inteligente Amazon Echo Dot', TRUE, 1, NOW()),
    (16, 'Razer BlackWidow V4', 169, 1, 'Teclado mecánico Razer BlackWidow V4 para gaming', TRUE, 1, NOW()),
    (17, 'Apple Mac Mini M2', 699, 1, 'Apple Mac Mini con chip M2', FALSE, 1, NOW()),
    (18, 'Asus ROG Phone 6', 999, 1, 'Móvil gamer Asus ROG Phone 6 con Snapdragon 8 Gen 1', TRUE, 1, NOW()),
    (19, 'Bose SoundLink Revolve', 199, 1, 'Altavoz Bluetooth Bose SoundLink Revolve con sonido envolvente', TRUE, 1, NOW()),
    (20, 'Garmin Fenix 7', 799, 1, 'Reloj deportivo Garmin Fenix 7 con GPS avanzado', FALSE, 1, NOW());

    INSERT INTO producto_imagenes (producto_id, imagen_url)
    VALUES 
    (1, '/assets/iphone13_1.webp'),
    (1, '/assets/iphone13_2.webp'),
    (1, '/assets/iphone13_3.webp'),
    (1, '/assets/iphone13_4.webp'),
    (1, '/assets/iphone13_5.webp'),
    (1, '/assets/iphone13_6.webp'),
    (2, '/assets/samsung_s21_1.webp'),
    (2, '/assets/samsung_s21_2.webp'),
    (2, '/assets/samsung_s21_3.webp'),
    (2, '/assets/samsung_s21_4.webp'),
    (3, '/assets/macbookpro_1.webp'),
    (3, '/assets/macbookpro_2.webp'),
    (4, '/assets/ipad4_1.webp'),
    (4, '/assets/ipad4_2.webp'),
    (4, '/assets/ipad4_3.webp'),
    (4, '/assets/ipad4_4.webp'),
    (4, '/assets/ipad4_5.webp'),
    (4, '/assets/ipad4_6.webp'),
    (4, '/assets/ipad4_7.webp'),
    (4, '/assets/ipad4_8.webp'),
    (4, '/assets/ipad4_9.webp'),
    (5, '/assets/googlepixel6.webp'),
    (5, '/assets/googlepixel6_2.webp'),
    (5, '/assets/googlepixel6_3.webp'),
    (5, '/assets/googlepixel6.webp'),
    (6, '/assets/ps5_1.webp'),
    (6, '/assets/ps5_2.webp'),
    (6, '/assets/ps5_3.webp'),
    (7, '/assets/xboxseriesx.webp'),
    (7, '/assets/xboxseriesx_2.webp'),
    (7, '/assets/xboxseriesx_3.webp'),
    (8, '/assets/dellxps13.webp'),
    (8, '/assets/dellxps13_2.webp'),
    (8, '/assets/dellxps13_3.webp'),
    (8, '/assets/dellxps13_4.webp'),
    (9, '/assets/applewatch7.webp'),
    (9, '/assets/applewatch7_2.webp'),
    (9, '/assets/applewatch7_3.webp'),
    (9, '/assets/applewatch7_4.webp'),
    (10, '/assets/airpodspro.webp'),
    (10, '/assets/airpodspro_2.webp'),
    (10, '/assets/airpodspro_3.webp'),
    (11, '/assets/galaxytabs8.webp'),
    (11, '/assets/galaxytabs8_2.webp'),
    (11, '/assets/galaxytabs8_3.webp'),
    (12, '/assets/lenovolegion5.webp'),
    (12, '/assets/lenovolegion5_2.webp'),
    (12, '/assets/lenovolegion5_3.webp'),
    (13, '/assets/goprohero10.webp'),
    (13, '/assets/goprohero10_2.webp'),
    (13, '/assets/goprohero10_3.webp'),
    (14, '/assets/sonywh1000xm4.webp'),
    (14, '/assets/sonywh1000xm4_2.webp'),
    (14, '/assets/sonywh1000xm4_3.webp'),
    (15, '/assets/amazonechodot.webp'),
    (15, '/assets/amazonechodot_2.webp'),
    (15, '/assets/amazonechodot_3.webp'),
    (16, '/assets/razerblackwidowv4.webp'),
    (16, '/assets/razerblackwidowv4_2.webp'),
    (16, '/assets/razerblackwidowv4_3.webp'),
    (17, '/assets/applemacmini.webp'),
    (17, '/assets/applemacmini_2.webp'),
    (17, '/assets/applemacmini_3.webp'),
    (18, '/assets/asusrogphone6.webp'),
    (18, '/assets/asusrogphone6_2.webp'),
    (18, '/assets/asusrogphone6_3.webp'),
    (19, '/assets/bosesoundlinkrevolve.webp'),
    (19, '/assets/bosesoundlinkrevolve_2.webp'),
    (19, '/assets/bosesoundlinkrevolve_3.webp'),
    (20, '/assets/garminfenix7.webp'),
    (20, '/assets/garminfenix7_2.webp'),
    (20, '/assets/garminfenix7_3.webp');
